Silverstripe\CMS\Model\SiteTree:
  extensions:
    - PurpleSpider\BasicSocialSharing\BasicSocialSharingExtension
PurpleSpider\BasicSocialSharing:
  default_title: "Title"
  default_description: "Content"